<?xml version="1.0"?>
<robot name="differential_wheeled_demo_robot" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:include filename="$(find demo_robot_description_pkg)/urdf/wheel2.urdf.xacro" /> 

<!--  Include Realsense Depth Sensor -->
<xacro:include filename="$(find demo_robot_description_pkg)/urdf/sensors/_d435.urdf.xacro" /> 

<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1"/>
  </material>


  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1"/>
  </material>

  <!-- PROPERTY LIST: Mass is in kg, len in m -->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />

  <!-- Base Properties -->
  <xacro:property name="base_mass" value="5.0" /> 
  <xacro:property name="base_height" value="0.080" /> 
  <xacro:property name="base_length" value="0.365" /> 
  <xacro:property name="base_width" value="0.15" /> 

  <!-- Mid Properties -->
  <xacro:property name="mid_mass" value="1.0" /> 
  <xacro:property name="mid_height" value="0.12" /> 
  <xacro:property name="mid_length" value="0.30" /> 
  <xacro:property name="mid_width" value="0.15" /> 

  <!-- Top Properties -->
  <xacro:property name="top_mass" value="0.50" /> 
  <xacro:property name="top_height" value="0.08" /> 
  <xacro:property name="top_length" value="0.15" /> 
  <xacro:property name="top_width" value="0.15" /> 

  <!-- Front Caster Wheel Properties -->
  <xacro:property name="caster_f_height" value="0.06" /> 
  <xacro:property name="caster_f_radius" value="0.03" /> 
  <xacro:property name="caster_f_mass" value="0.5" /> 

  <!-- Rear Caster Wheel Properties -->
  <xacro:property name="caster_b_height" value="0.06" /> 
  <xacro:property name="caster_b_radius" value="0.03" /> 
  <xacro:property name="caster_b_mass" value="0.5" /> 

  <!-- Side Wheels Properties -->
  <xacro:property name="wheel_mass" value="0" />
  <xacro:property name="base_x_origin_to_wheel_origin" value="0.08" />
  <xacro:property name="base_y_origin_to_wheel_origin" value="0.0" />
  <xacro:property name="base_z_origin_to_wheel_origin" value="0.0675" />

  <!-- Macro for calculating inertia of cylinder -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </xacro:macro>

  <!-- Base Footprint Link -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- Footprint->Base Joint -->
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${caster_b_radius + (base_height / 2)}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>
  
  <!-- Base Link -->
  <link name="base_link">
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0" 
          izz="0.0001" />
      <box size="${base_width} ${base_length} ${base_height}" />
    </inertial>    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <box size="${base_width} ${base_length} ${base_height}" />
      </geometry>
      <material name="White" />
    </visual>  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <box size="${base_width} ${base_length} ${base_height}" />
      </geometry>
    </collision>     
  </link>
  
  <gazebo reference="base_link">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- Base->Mid Joint -->
  <joint name="base_mid_joint" type="fixed">
    <origin xyz="0 0 ${base_height/2 + mid_height/2}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="mid_link" />
  </joint>

  <!-- Mid Link -->
  <link name="mid_link">
    <inertial>
      <mass value="${mid_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0" 
          izz="0.0001" />
      <box size="${mid_width} ${mid_length} ${mid_height}" />
    </inertial>    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <box size="${mid_width} ${mid_length} ${mid_height}" />
      </geometry>
      <material name="White" />
    </visual>  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <geometry>
          <box size="${mid_width} ${mid_length} ${mid_height}" />
      </geometry>
    </collision>     
  </link>

  <!-- Mid->Top Joint -->
  <joint name="mid_top_joint" type="fixed">
    <origin xyz="0 ${-top_length / 2} ${mid_height/2 + top_height/2}" rpy="0 0 0" />
    <parent link="mid_link"/>
    <child link="top_link" />
  </joint>

  <!-- Top Link -->
  <link name="top_link">
    <inertial>
      <mass value="${mid_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0" 
          izz="0.0001" />
      <box size="${top_width} ${top_length} ${top_height}" />
    </inertial>    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <box size="${top_width} ${top_length} ${top_height}" />
      </geometry>
      <material name="White" />
    </visual>  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <box size="${top_width} ${top_length} ${top_height}" />
      </geometry>
    </collision>     
  </link>

  <!-- D435 RGBD Camera -->
  <!-- Top->D435 RGBD Camera Joint -->
  <joint name="top_d435_joint" type="fixed">
    <origin xyz="0 ${top_length/2 + .015} ${top_height/2}" rpy="0 0 0" />
    <parent link="top_link"/>
    <child link="d435_link" />
  </joint>

  <!-- Top Link -->
  <link name="d435_link">
    <inertial>
      <mass value="${mid_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0" 
          izz="0.0001" />
      <box size="0.08 0.03 0.03" />
    </inertial>    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <box size="0.08 0.03 0.03" />
      </geometry>
      <material name="White" />
    </visual>  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <geometry>
          <box size="0.08 0.03 0.03" />
      </geometry>
    </collision>     
  </link>

  <sensor_d435 parent="d435_link">

  </sensor_d435>

  <!-- T265 Tracking Camera/IMU -->
  <!-- Top-T265 Joint -->
  <joint name="top_t265_joint" type="fixed">
    <origin xyz="0 ${top_length/2 + 0.005} ${top_height/2 - 0.03}" rpy="0 0 0" />
    <parent link="top_link"/>
    <child link="t265_link" />
  </joint>

  <!-- Top Link -->
  <link name="t265_link">
    <inertial>
      <mass value="${mid_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0" 
          izz="0.0001" />
      <box size="0.08 0.01 0.03" />
    </inertial>    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <box size="0.08 0.01 0.03" />
      </geometry>
      <material name="White" />
    </visual>  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <geometry>
          <box size="0.08 0.01 0.03" />
      </geometry>
    </collision>     
  </link>

  <!-- Front-Downward-Facing Mono Camera -->
  
  <!-- Right Mono Camera 1 -->
  
  <!-- Right Mono Camera 2 -->
  <!-- Left Mono Camera 1 -->
  <!-- Left Mono Camera 2 -->

  
  <gazebo reference="top_link">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- Front Castor wheel -->
  <link name="caster_front_link">
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
				<sphere radius="${caster_f_radius}" />
      </geometry>
      <material name="Black" />
    </visual>  
    <collision>
      <geometry>
				<sphere radius="${caster_f_radius}" />
      </geometry>
    <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
    </collision>      
    <inertial>
      <mass value="${caster_f_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" 
               izz="0.001" />
    </inertial>
  </link>

	<joint name="caster_front_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_front_link"/>
    <origin xyz="0.0 0.15 -.03" rpy="${-M_PI/2} 0 0"/>
  </joint>

  <gazebo reference="caster_front_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <link name="caster_back_link">
  <visual>
    <origin xyz="0 0 0 " rpy="${M_PI/2} 0 0" /> 
    <geometry>
			<sphere radius="${caster_b_radius}" />
    </geometry>
    <material name="Black" />
  </visual>  
  <collision>
    <geometry>
			<sphere radius="${caster_b_radius}" />
     </geometry>
     <origin xyz="0 0 0 " rpy="${M_PI/2} 0 0" /> 
    </collision>      
    <inertial>
      <mass value="${caster_b_mass}" />
      <origin xyz="0 0 0" />        
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" 
               izz="0.001" />
    </inertial>
  </link>

  <joint name="caster_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_link"/>
    <origin xyz="0 -0.15 -${caster_b_radius}" rpy="${-M_PI/2} 0 0"/>
  </joint>

  <gazebo reference="caster_back_link">
   <turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <!-- Left Wheel -->
  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0  ${M_PI/2} " /> 
      <geometry>
        <cylinder length="${0.04}" radius="${0.135}" />
      </geometry>
      <material name="Red" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2} " />
      <geometry>
        <cylinder length="${0.04}" radius="${0.04}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
              iyy="0.001" iyz="0.0" 
              izz="0.001" />
    </inertial>
  </link>

  <!-- Left Wheel Joint -->
	<joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.096 0 ${base_z_origin_to_wheel_origin}" rpy="${-M_PI/2} 0 0"/>
  </joint>

  <!-- Right Wheel -->
  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0  ${M_PI/2} " /> 
      <geometry>
        <cylinder length="${0.04}" radius="${0.135}" />
      </geometry>
      <material name="Red" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2} " />
      <geometry>
        <cylinder length="${0.04}" radius="${0.04}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
              iyy="0.001" iyz="0.0" 
              izz="0.001" />
    </inertial>
  </link>

  <!-- Right Wheel Joint -->
	<joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="-0.096 0 ${base_z_origin_to_wheel_origin}" rpy="${-M_PI/2} 0 0"/>
  </joint>

  <!-- Wheel Transmission -->
  <transmission name="wheel_left_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel_left_joint" />
    <actuator name="$wheel_left_joint_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="wheel_right_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel_right_joint" />
    <actuator name="$wheel_right_joint_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Gazebo Differential Drive Controller -->
	<gazebo>
  	<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
	    <legacyMode>true</legacyMode>
	    <rosDebugLevel>Debug</rosDebugLevel>
	    <publishWheelTF>false</publishWheelTF>
	    <robotNamespace>/</robotNamespace>
	    <publishTf>1</publishTf>
	    <publishWheelJointState>false</publishWheelJointState>
	    <alwaysOn>true</alwaysOn>
	    <updateRate>100.0</updateRate>
	    <leftJoint>wheel_left_joint</leftJoint>
	    <rightJoint>wheel_right_joint</rightJoint>
	    <wheelSeparation>${2*base_width}</wheelSeparation>
	    <wheelDiameter>${2*wheel_radius}</wheelDiameter>
	    <broadcastTF>1</broadcastTF>
	    <wheelTorque>30</wheelTorque>
	    <wheelAcceleration>1.8</wheelAcceleration>
	    <commandTopic>cmd_vel</commandTopic>
	    <odometryFrame>odom</odometryFrame> 
	    <odometryTopic>odom</odometryTopic> 
	    <robotBaseFrame>base_footprint</robotBaseFrame>
   </plugin>
  </gazebo> 
</robot>